scraper_name: bitcoinbeach
base_url: https://www.bitcoinbeach.com/summit-blog/bitcoin-circular-economies-summit-2026
events_url: https://www.bitcoinbeach.com/summit-blog/bitcoin-circular-economies-summit-2026
categories:
- bitcoin only
